name: Version Update and Upload Python Package

#Upload to pypi when tagged release.
#Requirements:
#・Add this file to "trusted publishers" in pypi and test pypi.
#・Version.txt exists in root



on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          ref: main
          fetch-depth: 0
          
    - name: version_print  
      run: |
        version=$(cat version.txt)
        echo "Version0!!!!!!!: $version"
        echo "final_version=1.2.9" >> $GITHUB_OUTPUT

    - name: Set version as environment variable
      run: echo "VERSION=1.2.9" >> $GITHUB_ENV

    - name: Update VERSION file
      run: echo "${{ steps.determine_version.outputs.final_version }}" > Version.txt

    - name: Commit
      run: |
        version=$(cat version.txt)
        echo "Version1: $version"
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git pull origin main
        git add Version.txt
        git commit -m "Update Version.txt file to ${{ steps.determine_version.outputs.final_version }}"
        git push origin main
        version_two=$(cat version.txt)
        echo "Version2: $version_two"
